# Generated by Django 5.2.1 on 2025-05-13 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_accessory_image_alter_device_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessory',
            name='description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='device',
            name='description',
            field=models.CharField(max_length=255),
        ),
    ]
